export const HTML_ELEMENT_ATTRIBUTES: Record<string, Array<string>> = {
    '*': [
        'accesskey',
        'autocapitalize',
        'class',
        'contenteditable',
        'contextmenu',
        'data-*',
        'dir',
        'draggable',
        'hidden',
        'id',
        'itemprop',
        'lang',
        'role',
        'slot',
        'spellcheck',
        'style',
        'tabindex',
        'title',
        'translate'
    ],
    a: [
        'download',
        'href',
        'hreflang',
        'media',
        'ping',
        'referrerpolicy',
        'rel',
        'shape',
        'target'
    ],
    abbr: [],
    acronym: [],
    address: [],
    applet: ['align', 'alt', 'code', 'codebase'],
    area: [
        'alt',
        'coords',
        'download',
        'href',
        'hreflang',
        'media',
        'ping',
        'referrerpolicy',
        'rel',
        'shape',
        'target'
    ],
    article: [],
    aside: [],
    audio: [
        'autoplay',
        'buffered',
        'controls',
        'crossorigin',
        'loop',
        'muted',
        'preload',
        'src'
    ],
    b: [],
    base: ['href', 'target'],
    basefont: ['color'],
    bdi: [],
    bdo: [],
    bgsound: ['loop'],
    big: [],
    blink: [],
    blockquote: ['cite'],
    body: ['background', 'bgcolor'],
    br: [],
    button: [
        'autofocus',
        'disabled',
        'form',
        'formaction',
        'formenctype',
        'formmethod',
        'formnovalidate',
        'formtarget',
        'name',
        'type',
        'value'
    ],
    canvas: ['height', 'width'],
    caption: ['align'],
    center: [],
    cite: [],
    code: [],
    col: ['align', 'bgcolor', 'span'],
    colgroup: ['align', 'bgcolor', 'span'],
    command: ['checked', 'disabled', 'icon', 'radiogroup', 'type'],
    content: [],
    contenteditable: ['enterkeyhint', 'inputmode'],
    data: ['value'],
    datalist: [],
    dd: [],
    del: ['cite', 'datetime'],
    details: ['open'],
    dfn: [],
    dialog: ['open'],
    dir: [],
    div: [],
    dl: [],
    dt: [],
    em: [],
    embed: ['height', 'src', 'type', 'width'],
    fieldset: ['disabled', 'form', 'name'],
    figcaption: [],
    figure: [],
    font: ['color'],
    footer: [],
    form: [
        'accept',
        'accept-charset',
        'action',
        'autocomplete',
        'enctype',
        'method',
        'name',
        'novalidate',
        'target'
    ],
    frame: [],
    frameset: [],
    h1: [],
    h2: [],
    h3: [],
    h4: [],
    h5: [],
    h6: [],
    head: [],
    header: [],
    hgroup: [],
    hr: ['align', 'color'],
    html: ['manifest'],
    i: [],
    iframe: [
        'align',
        'allow',
        'csp',
        'height',
        'importance',
        'loading',
        'name',
        'referrerpolicy',
        'sandbox',
        'src',
        'srcdoc',
        'width'
    ],
    image: [],
    img: [
        'align',
        'alt',
        'border',
        'crossorigin',
        'decoding',
        'height',
        'importance',
        'intrinsicsize',
        'ismap',
        'loading',
        'referrerpolicy',
        'sizes',
        'src',
        'srcset',
        'usemap',
        'width'
    ],
    input: [
        'accept',
        'alt',
        'autocomplete',
        'autofocus',
        'capture',
        'checked',
        'dirname',
        'disabled',
        'form',
        'formaction',
        'formenctype',
        'formmethod',
        'formnovalidate',
        'formtarget',
        'height',
        'list',
        'max',
        'maxlength',
        'minlength',
        'min',
        'multiple',
        'name',
        'pattern',
        'placeholder',
        'readonly',
        'required',
        'size',
        'src',
        'step',
        'type',
        'usemap',
        'value',
        'width'
    ],
    ins: ['cite', 'datetime'],
    kbd: [],
    keygen: ['autofocus', 'challenge', 'disabled', 'form', 'keytype', 'name'],
    label: ['for', 'form'],
    legend: [],
    li: ['value'],
    link: [
        'crossorigin',
        'href',
        'hreflang',
        'importance',
        'integrity',
        'media',
        'referrerpolicy',
        'rel',
        'sizes',
        'type'
    ],
    main: [],
    map: ['name'],
    mark: [],
    marquee: ['bgcolor', 'loop'],
    math: [],
    menu: ['type'],
    menuitem: [],
    meta: ['charset', 'content', 'http-equiv', 'name'],
    meter: ['form', 'high', 'low', 'max', 'min', 'optimum', 'value'],
    nav: [],
    nobr: [],
    noembed: [],
    noframes: [],
    noscript: [],
    object: [
        'border',
        'data',
        'form',
        'height',
        'name',
        'type',
        'usemap',
        'width'
    ],
    ol: ['reversed', 'start'],
    optgroup: ['disabled', 'label'],
    option: ['disabled', 'label', 'selected', 'value'],
    output: ['for', 'form', 'name'],
    p: [],
    param: ['name', 'value'],
    picture: [],
    plaintext: [],
    portal: [],
    pre: [],
    progress: ['form', 'max', 'value'],
    q: ['cite'],
    rb: [],
    rp: [],
    rt: [],
    rtc: [],
    ruby: [],
    s: [],
    samp: [],
    script: [
        'async',
        'charset',
        'crossorigin',
        'defer',
        'importance',
        'integrity',
        'language',
        'referrerpolicy',
        'src',
        'type'
    ],
    section: [],
    select: [
        'autocomplete',
        'autofocus',
        'disabled',
        'form',
        'multiple',
        'name',
        'required',
        'size'
    ],
    shadow: [],
    slot: [],
    small: [],
    source: ['media', 'sizes', 'src', 'srcset', 'type'],
    spacer: [],
    span: [],
    strike: [],
    strong: [],
    style: ['media', 'scoped', 'type'],
    sub: [],
    summary: [],
    sup: [],
    svg: [],
    table: ['align', 'background', 'bgcolor', 'border', 'summary'],
    tbody: ['align', 'bgcolor'],
    td: ['align', 'background', 'bgcolor', 'colspan', 'headers', 'rowspan'],
    template: [],
    textarea: [
        'autocomplete',
        'autofocus',
        'cols',
        'dirname',
        'disabled',
        'enterkeyhint',
        'form',
        'inputmode',
        'maxlength',
        'minlength',
        'name',
        'placeholder',
        'readonly',
        'required',
        'rows',
        'wrap'
    ],
    tfoot: ['align', 'bgcolor'],
    th: [
        'align',
        'background',
        'bgcolor',
        'colspan',
        'headers',
        'rowspan',
        'scope'
    ],
    thead: ['align'],
    time: ['datetime'],
    title: [],
    tr: ['align', 'bgcolor'],
    track: ['default', 'kind', 'label', 'src', 'srclang'],
    tt: [],
    u: [],
    ul: [],
    var: [],
    video: [
        'autoplay',
        'buffered',
        'controls',
        'crossorigin',
        'height',
        'loop',
        'muted',
        'poster',
        'preload',
        'src',
        'width'
    ],
    wbr: [],
    xmp: []
}

export const TAG_NAMES = [
    'a',
    'abbr',
    'acronym',
    'address',
    'applet',
    'area',
    'article',
    'aside',
    'audio',
    'b',
    'base',
    'basefont',
    'bdi',
    'bdo',
    'bgsound',
    'big',
    'blink',
    'blockquote',
    'body',
    'br',
    'button',
    'canvas',
    'caption',
    'center',
    'cite',
    'code',
    'col',
    'colgroup',
    'command',
    'content',
    'contenteditable',
    'data',
    'datalist',
    'dd',
    'del',
    'details',
    'dfn',
    'dialog',
    'dir',
    'div',
    'dl',
    'dt',
    'em',
    'embed',
    'fieldset',
    'figcaption',
    'figure',
    'font',
    'footer',
    'form',
    'frame',
    'frameset',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'head',
    'header',
    'hgroup',
    'hr',
    'html',
    'i',
    'iframe',
    'image',
    'img',
    'input',
    'ins',
    'kbd',
    'keygen',
    'label',
    'legend',
    'li',
    'link',
    'main',
    'map',
    'mark',
    'marquee',
    'math',
    'menu',
    'menuitem',
    'meta',
    'meter',
    'nav',
    'nobr',
    'noembed',
    'noframes',
    'noscript',
    'object',
    'ol',
    'optgroup',
    'option',
    'output',
    'p',
    'param',
    'picture',
    'plaintext',
    'portal',
    'pre',
    'progress',
    'q',
    'rb',
    'rp',
    'rt',
    'rtc',
    'ruby',
    's',
    'samp',
    'script',
    'section',
    'select',
    'shadow',
    'slot',
    'small',
    'source',
    'spacer',
    'span',
    'strike',
    'strong',
    'style',
    'sub',
    'summary',
    'sup',
    'svg',
    'table',
    'tbody',
    'td',
    'template',
    'textarea',
    'tfoot',
    'th',
    'thead',
    'time',
    'title',
    'tr',
    'track',
    'tt',
    'u',
    'ul',
    'var',
    'video',
    'wbr',
    'xmp'
]

export const EVENT_NAMES = [
    'cached',
    'error',
    'abort',
    'load',
    'beforeunload',
    'unload',
    'online',
    'offline',
    'focus',
    'blur',
    'open',
    'message',
    'close',
    'pagehide',
    'pageshow',
    'popstate',
    'animationstart',
    'animationend',
    'animationiteration',
    'transitionstart',
    'transitioncancel',
    'transitionend',
    'transitionrun',
    'reset',
    'submit',
    'beforeprint',
    'afterprint',
    'compositionstart',
    'compositionupdate',
    'compositionend',
    'fullscreenchange',
    'fullscreenerror',
    'resize',
    'scroll',
    'cut',
    'copy',
    'paste',
    'Event',
    'keydown',
    'keypress',
    'keyup',
    'mouseenter',
    'mouseover',
    'mousemove',
    'mousedown',
    'mouseup',
    'auxclick',
    'click',
    'dblclick',
    'contextmenu',
    'wheel',
    'mouseleave',
    'mouseout',
    'select',
    'pointerlockchange',
    'pointerlockerror',
    'dragstart',
    'drag',
    'dragend',
    'dragenter',
    'dragover',
    'dragleave',
    'drop',
    'durationchange',
    'loadedmetadata',
    'loadeddata',
    'canplay',
    'canplaythrough',
    'ended',
    'emptied',
    'stalled',
    'suspend',
    'play',
    'playing',
    'pause',
    'waiting',
    'seeking',
    'seeked',
    'ratechange',
    'timeupdate',
    'volumechange',
    'complete',
    'audioprocess',
    'loadstart',
    'progress',
    'timeout',
    'loadend',
    'change',
    'storage',
    'checking',
    'downloading',
    'noupdate',
    'obsolete',
    'updateready',
    'broadcast',
    'CheckboxStateChange',
    'hashchange',
    'input',
    'RadioStateChange',
    'readystatechange',
    'ValueChange',
    'invalid',
    'localized',
    'show',
    'SVGAbort',
    'SVGError',
    'SVGLoad',
    'SVGResize',
    'SVGScroll',
    'SVGUnload',
    'SVGZoom',
    'blocked',
    'success',
    'upgradeneeded',
    'versionchange',
    'AlertActive',
    'AlertClose',
    'CssRuleViewRefreshed',
    'CssRuleViewChanged',
    'CssRuleViewCSSLinkClicked',
    'afterscriptexecute',
    'beforescriptexecute',
    'DOMMenuItemActive',
    'DOMMenuItemInactive',
    'DOMWindowCreated',
    'DOMTitleChanged',
    'DOMWindowClose',
    'SSWindowClosing',
    'SSWindowStateReady',
    'SSWindowStateBusy',
    'DOMLinkAdded',
    'DOMLinkRemoved',
    'DOMMetaAdded',
    'DOMMetaRemoved',
    'DOMWillOpenModalDialog',
    'DOMModalDialogClosed',
    'popuphidden',
    'popuphiding',
    'popupshowing',
    'popupshown',
    'DOMPopupBlocked',
    'TabOpen',
    'TabClose',
    'TabSelect',
    'TabShow',
    'TabHide',
    'TabPinned',
    'TabUnpinned',
    'SSTabClosing',
    'SSTabRestoring',
    'SSTabRestored',
    'visibilitychange',
    'chargingchange',
    'chargingtimechange',
    'dischargingtimechange',
    'levelchange',
    'alerting',
    'busy',
    'callschanged',
    'cfstatechange',
    'connected',
    'connecting',
    'dialing',
    'disconnected',
    'disconnecting',
    'held',
    'incoming',
    'resuming',
    'statechange',
    'voicechange',
    'compassneedscalibration',
    'devicelight',
    'devicemotion',
    'deviceorientation',
    'deviceproximity',
    'MozOrientation',
    'orientationchange',
    'userproximity',
    'icccardlockerror',
    'iccinfochange',
    'smartcard-insert',
    'smartcard-remove',
    'stkcommand',
    'stksessionend',
    'cardstatechange',
    'delivered',
    'received',
    'sent',
    'ussdreceived',
    'mozbrowserclose',
    'mozbrowsercontextmenu',
    'mozbrowsererror',
    'mozbrowsericonchange',
    'mozbrowserlocationchange',
    'mozbrowserloadend',
    'mozbrowserloadstart',
    'mozbrowseropenwindow',
    'mozbrowsersecuritychange',
    'mozbrowsershowmodalprompt',
    'mozbrowsertitlechange',
    'DOMFrameContentLoaded',
    'DOMAttributeNameChanged',
    'DOMAttrModified',
    'DOMCharacterDataModified',
    'DOMContentLoaded',
    'DOMElementNameChanged',
    'DOMNodeInserted',
    'DOMNodeInsertedIntoDocument',
    'DOMNodeRemoved',
    'DOMNodeRemovedFromDocument',
    'DOMSubtreeModified',
    'MozEdgeUIGesture',
    'MozMagnifyGesture',
    'MozMagnifyGestureStart',
    'MozMagnifyGestureUpdate',
    'MozPressTapGesture',
    'MozRotateGesture',
    'MozRotateGestureStart',
    'MozRotateGestureUpdate',
    'MozSwipeGesture',
    'MozTapGesture',
    'MozTouchDown',
    'MozTouchMove',
    'MozTouchUp',
    'touchcancel',
    'touchend',
    'touchenter',
    'touchleave',
    'touchmove',
    'touchstart',
    'pointerover',
    'pointerenter',
    'pointerdown',
    'pointermove',
    'pointerup',
    'pointercancel',
    'pointerout',
    'pointerleave',
    'gotpointercapture',
    'lostpointercapture',
    'appinstalled',
    'audioend',
    'audiostart',
    'beginEvent',
    'boundary',
    'devicechange',
    'DOMActivate',
    'DOMFocusIn',
    'DOMFocusOut',
    'end',
    'endEvent',
    'focusinUnimplemented',
    'focusoutUnimplemented',
    'gamepadconnected',
    'gamepaddisconnected',
    'languagechange',
    'mark',
    'nomatch',
    'notificationclick',
    'push',
    'pushsubscriptionchange',
    'repeatEvent',
    'resourcetimingbufferfull',
    'result',
    'resume',
    'selectstart',
    'selectionchange',
    'soundend',
    'soundstart',
    'speechend',
    'speechstart',
    'start',
    'voiceschanged',
    'vrdisplayconnected',
    'vrdisplaydisconnected',
    'vrdisplaypresentchange',
    'beforeinstallprompt',
    'connectionInfoUpdate',
    'datachange',
    'dataerror',
    'DOMMouseScroll',
    'dragdrop',
    'dragexit',
    'draggesture',
    'mousewheel',
    'MozAudioAvailable',
    'MozBeforeResize',
    'mozbrowseractivitydone',
    'mozbrowserasyncscroll',
    'mozbrowseraudioplaybackchange',
    'mozbrowsercaretstatechanged',
    'mozbrowserdocumentfirstpaint',
    'mozbrowserfindchange',
    'mozbrowserfirstpaint',
    'mozbrowsermanifestchange',
    'mozbrowsermetachange',
    'mozbrowseropensearch',
    'mozbrowseropentab',
    'mozbrowserresize',
    'mozbrowserscroll',
    'mozbrowserscrollareachanged',
    'mozbrowserscrollviewchange',
    'mozbrowserselectionstatechanged',
    'mozbrowserusernameandpasswordrequired',
    'mozbrowservisibilitychange',
    'MozGamepadButtonDown',
    'MozGamepadButtonUp',
    'MozMousePixelScroll',
    'MozScrolledAreaChanged',
    'moztimechange',
    'onconnected',
    'disabled',
    'enabled',
    'held',
    'holding',
    'statuschange',
    'overflow',
    'text',
    'underflow',
    'uploadprogress',
    'command',
    'commandupdate',
    'MozAfterPaint',
    'DOMAutoComplete',
    'fullscreen',
    'sizemodechange',
    'MozEnteredDomFullscreen'
]
